-- Create or replace the temporary table
CREATE OR REPLACE TEMPORARY TABLE temp_product (
    PRODUCTID NUMBER(38,0),
    PRODUCTNAME VARCHAR(40),
    LISTPRICE FLOAT,
    UNITCOST FLOAT,
    DISCONTINUED VARCHAR(3),
    CATEGORYNAME VARCHAR(15),
    SUPPLIER VARCHAR(30),
    UNIQUE (PRODUCTID)
);


INSERT INTO temp_product (PRODUCTID, PRODUCTNAME, LISTPRICE, UNITCOST, DISCONTINUED, CATEGORYNAME, SUPPLIER)
SELECT
    "Product ID" AS PRODUCTID,
    "Product Name" AS PRODUCTNAME,
    "ListPrice" AS LISTPRICE,
    "UnitCost" AS UNITCOST,
    "Discontinued" AS DISCONTINUED,
    "CategoryName" AS CATEGORYNAME,
    "Supplier" AS SUPPLIER
FROM @~/migrations/product_fresh.csv;


-- Drop columns from PRODUCT table
ALTER TABLE PRODUCT
DROP COLUMN IF EXISTS
    SUPPLIERID,
    CATEGORYID,
    QUANTITYPERUNIT,
    UNITSINSTOCK,
    UNITSONORDER,
    REORDERLEVEL,
    DISCONTINUED;

-- Rename UNITPRICE to LISTPRICE in PRODUCT table
ALTER TABLE PRODUCT
RENAME COLUMN UNITPRICE TO LISTPRICE;

-- Add columns to PRODUCT table
ALTER TABLE PRODUCT
ADD COLUMN IF NOT EXISTS
    UNITCOST FLOAT DEFAULT NULL,
    DISCONTINUED VARCHAR(3) DEFAULT NULL,
    CATEGORYNAME VARCHAR(15) DEFAULT NULL,
    SUPPLIER VARCHAR(30) DEFAULT NULL;


-- Update data in PRODUCT table from temp_product
UPDATE PRODUCT p
SET
    p.PRODUCTNAME = (SELECT tp.PRODUCTNAME FROM temp_product tp WHERE p.PRODUCTID = tp.PRODUCTID),
    p.UNITCOST = (SELECT tp.UNITCOST FROM temp_product tp WHERE p.PRODUCTID = tp.PRODUCTID),
    p.DISCONTINUED = (SELECT tp.DISCONTINUED FROM temp_product tp WHERE p.PRODUCTID = tp.PRODUCTID),
    p.CATEGORYNAME = (SELECT tp.CATEGORYNAME FROM temp_product tp WHERE p.PRODUCTID = tp.PRODUCTID),
    p.SUPPLIER = (SELECT tp.SUPPLIER FROM temp_product tp WHERE p.PRODUCTID = tp.PRODUCTID);

