CREATE OR REPLACE TEMPORARY TABLE temp_product (
    "Product ID" NUMBER(38,0),
    "Product Name" VARCHAR(40),
    ListPrice FLOAT,
    UnitCost FLOAT,
    Discontinued VARCHAR(3),
    CategoryName VARCHAR(15),
    Supplier VARCHAR(40)
);

COPY INTO temp_product ("Product ID", "Product Name", ListPrice, UnitCost, Discontinued, CategoryName, Supplier)
FROM @PRODUCT_FRESH/product_fresh.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER = 1);

-- Drop columns from PRODUCT table
ALTER TABLE PRODUCT
DROP COLUMN IF EXISTS
    SUPPLIERID,
    CATEGORYID,
    QUANTITYPERUNIT,
    UNITSINSTOCK,
    UNITSONORDER,
    REORDERLEVEL,
    DISCONTINUED;

-- Rename UNITPRICE to LISTPRICE in PRODUCT table
ALTER TABLE PRODUCT
RENAME COLUMN UNITPRICE TO LISTPRICE;

-- Add columns to PRODUCT table
ALTER TABLE PRODUCT
ADD COLUMN IF NOT EXISTS
    UNITCOST FLOAT DEFAULT NULL,
    DISCONTINUED VARCHAR(3) DEFAULT NULL,
    CATEGORYNAME VARCHAR(15) DEFAULT NULL,
    SUPPLIER VARCHAR(40) DEFAULT NULL;


MERGE INTO PRODUCT AS p
USING temp_product AS tp
ON p.PRODUCTID = tp."Product ID"
WHEN MATCHED THEN
  UPDATE SET
    p.PRODUCTNAME = tp."Product Name",
    p.UNITCOST = tp.UNITCOST,
    p.DISCONTINUED = tp.DISCONTINUED,
    p.CATEGORYNAME = tp.CATEGORYNAME,
    p.SUPPLIER = tp.SUPPLIER;



