SELECT 
    p.CATEGORYNAME AS CATEGORYNAME,
    o.ORDERDATE AS ORDERDATE,
    COUNT(od.ORDERID) AS ORDERCOUNT,
    SUM(od.QUANTITY) AS QUANTITY,
    ROUND(SUM(od.REVENUE),1) as REVENUE,
    ROUND(SUM(od.PROFIT),1) as PROFIT
FROM
    {{ref('raw_product')}} p
    INNER JOIN {{ref('stg_order_detail')}} od ON p.PRODUCTID = od.PRODUCTID
    INNER JOIN {{ref('stg_orders')}} o ON od.ORDERID = o.ORDERID
GROUP BY
    p.CATEGORYNAME, o.ORDERDATE
 