SELECT
    o.ORDERID as ORDERID,
    o.ORDERDATE as ORDERDATE,
    o.ORDERDAY as ORDERDAY,
    o.ORDERMONTH as ORDERMONTH,
    o.ORDERYEAR as ORDERYEAR,
    ROUND(SUM(od.NETSALES),1) as NETSALES
FROM
    {{ref ('stg_orders')}} o
    INNER JOIN {{ref ('stg_order_detail')}} od ON o.ORDERID = od.ORDERID
WHERE
    o.SHIPPEDDATE IS NOT NULL
GROUP BY
    o.ORDERID, o.ORDERDATE, o.ORDERDAY, o.ORDERMONTH, o.ORDERYEAR

