name: cfai-ci-cd

# Defines the events that will trigger the workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trigger-dbt-cloud-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Trigger dbt Cloud Job
      run: |
        # Use the dbt Cloud API to trigger the job
        response=$(curl -X POST https://cloud.getdbt.com/api/v2/accounts/239132/jobs/512170/run/ \
          -H "Authorization: Token ${DBT_CLOUD_API_TOKEN}" \
          -H "Content-Type: application/json" \
          --data '{"cause": "Triggered from GitHub Actions"}' \
          --silent)
        
        # Check if the API call was successful
        job_run_id=$(echo $response | jq .data.id)
        if [ "$job_run_id" != "null" ]; then
          echo "Triggered dbt Cloud job successfully, run ID: $job_run_id"
        else
          echo "Failed to trigger dbt Cloud job"
          echo "Response: $response"
          exit 1
        fi

      env:
        DBT_CLOUD_API_TOKEN: ${{ secrets.DBT_CLOUD_API_TOKEN_CFAI }}

